name: item-manager-node

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file: ./.env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=mongodb
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
    networks:
      - net

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_DATABASE
    volumes:
      - db:/data/db
    networks:
      - net

volumes:
  db:

networks:
  net:
    driver: bridge
