version: "3.9"
services:

  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=mongodb
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE

  mongodb:
    image: mongo:7
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db:/data/db

volumes:
  db: