name: item-manager-node

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    #environment:
    #- MONGO_INITDB_ROOT_USERNAME=admin
    #- MONGO_INITDB_ROOT_PASSWORD=password
    #- MONGO_INITDB_DATABASE=itemdb
    volumes:
      - mongo_data:/data/db
    networks:
      - itemnet

  node_app:
    build: .
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    env_file: ./.env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=mongo_db
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
    networks:
      - itemnet

volumes:
  mongo_data:

networks:
  itemnet:
    driver: bridge
